# Generated by Django 5.1 on 2024-08-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя мастера')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия мастера')),
                ('contact_info', models.TextField(max_length=30, verbose_name='Контактная информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/photos/', verbose_name='Фото мастера')),
                ('services', models.ManyToManyField(related_name='masters', to='core.service')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Телефон клиента')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='core.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.service')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
