# Generated by Django 5.1 on 2024-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_options_alter_master_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/photos/', verbose_name='Фото мастера'),
        ),
    ]
