# Generated by Django 5.1 on 2024-08-28 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_master_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='contact_info',
            field=models.TextField(max_length=200, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters/photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.IntegerField(choices=[(0, 'Не подтверждена'), (1, 'Подтверждена'), (2, 'Отменена'), (3, 'Выполнена')], default=0, verbose_name='Статус')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.master', verbose_name='Мастер')),
                ('services', models.ManyToManyField(to='core.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
